# Generated by Django 4.2.1 on 2023-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20, unique=True)),
                ('prenom', models.CharField(default='', max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=6)),
            ],
        ),
    ]
