# Generated by Django 4.2.5 on 2023-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_room_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
