# Generated by Django 4.2.1 on 2023-09-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Eleve',
        ),
    ]
